// Common allergies that users can select from
export const COMMON_ALLERGIES = [
  'Penicillin',
  'Amoxicillin',
  'Aspirin',
  'Ibuprofen',
  'Codeine',
  'Sulfa drugs',
  'Tetracycline',
  'Latex',
  'Peanuts',
  'Tree nuts',
  'Shellfish',
  'Eggs',
  'Milk',
  'Soy',
  'Wheat',
  'Fish',
  'Sesame',
  'Bee stings',
  'Wasp stings',
  'Pollen',
  'Dust mites',
  'Mold',
  'Pet dander',
  'Nickel',
  'Fragrances',
  'Dyes',
].sort();

// Common medical conditions that users can select from
export const COMMON_CONDITIONS = [
  'Diabetes Type 1',
  'Diabetes Type 2',
  'Hypertension (High Blood Pressure)',
  'Hypotension (Low Blood Pressure)',
  'Asthma',
  'COPD (Chronic Obstructive Pulmonary Disease)',
  'Heart Disease',
  'Coronary Artery Disease',
  'Atrial Fibrillation',
  'Heart Failure',
  'Stroke',
  'High Cholesterol',
  'Obesity',
  'Arthritis',
  'Rheumatoid Arthritis',
  'Osteoarthritis',
  'Osteoporosis',
  'Thyroid Disorder',
  'Hypothyroidism',
  'Hyperthyroidism',
  'Kidney Disease',
  'Liver Disease',
  'GERD (Acid Reflux)',
  'Irritable Bowel Syndrome (IBS)',
  'Crohn\'s Disease',
  'Ulcerative Colitis',
  'Celiac Disease',
  'Depression',
  'Anxiety',
  'Bipolar Disorder',
  'Schizophrenia',
  'ADHD',
  'Epilepsy',
  'Migraine',
  'Parkinson\'s Disease',
  'Alzheimer\'s Disease',
  'Multiple Sclerosis',
  'Lupus',
  'Fibromyalgia',
  'Cancer',
  'Anemia',
  'Sleep Apnea',
  'Glaucoma',
  'Cataracts',
  'Psoriasis',
  'Eczema',
  'HIV/AIDS',
  'Hepatitis B',
  'Hepatitis C',
].sort();
